# permissions for end users to edit kustomizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kustomization-editor-role
rules:
  - apiGroups:
      - kustomize.siliconhills.dev
    resources:
      - kustomizations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kustomize.siliconhills.dev
    resources:
      - kustomizations/status
    verbs:
      - get
